### PR TITLE
Don't require optional sync fields in responses

### PR DESCRIPTION
**Pull request by Fizzadar**
Remove some checks for fields that are not required in sync responses.

Signed off by Nick @ Beeper (@Fizzadar).

### CODE REVIEW

**Review by DMRobertson — APPROVED** [review]
Seems consistent with https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv3sync to me. Many thanks!

**Comment by DMRobertson** [comment]
@Fizzadar before I merge, can you [sign-off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off) on this please? (I will update the complement repo to ask PR authors do so as much)

**Comment by DMRobertson** [comment]
> will update the complement repo to ask PR authors do so as much

#598

**Comment by Fizzadar** [comment]
@DMRobertson sign-off added!

**Pull request merged**
