### PR TITLE
feat: add room_membership tests

### PR DESCRIPTION
**Pull request by meenal06**
Signed-off-by: Meenal Trivedi <meenaltrivedi6102@gmail.com>

### CODE REVIEW

**Comment by meenal06** [comment]
@kegsay please review

**Review by kegsay — CHANGES_REQUESTED** [review]
Same comments apply for the other subtests.

**Comment by meenal06** [comment]
Hey @kegsay all the requested changes have been taken care of

**Review by kegsay — APPROVED** [review]
Excellent, thank you!

**Pull request merged**
