### PR TITLE
feat: add avatar_url tests

### PR DESCRIPTION
**Pull request by meenal06**
Signed-off-by: Meenal Trivedi <meenaltrivedi6102@gmail.com>

### CODE REVIEW

**Comment by meenal06** [comment]
@kegsay Review please!

**Review by kegsay — CHANGES_REQUESTED** [review]
See comments on https://github.com/matrix-org/complement/pull/130 which are applicable here.

**Comment by meenal06** [comment]
@kegsay I have fixed this PR too

**Comment by meenal06** [comment]
@kegsay ping

**Review by kegsay — APPROVED** [review]

**Pull request merged**
