### PR TITLE
Test aliases during a partial join resync

### PR DESCRIPTION
**Pull request by DMRobertson**
Synapse Issue: https://github.com/matrix-org/synapse/issues/13287
Synapse PR: https://github.com/matrix-org/synapse/pull/14292

### CODE REVIEW

**Review by erikjohnston — APPROVED** [review]

**Comment by DMRobertson** [comment]
Going to wait for the Synapse change to land before merging this.

**Comment by DMRobertson** [comment]
I've added in another test case. Sean, would you mind taking a quick look?

**Review by squahtx — APPROVED** [review]
The additional test case lgtm

**Comment by DMRobertson** [comment]
Cheers!

**Pull request merged**
