### PR TITLE
Integration test for m.login.sso

### PR DESCRIPTION
**Pull request by tommie**
For https://github.com/matrix-org/dendrite/pull/2492.

### CODE REVIEW

**Comment by richvdh** [comment]
@tommie are you still interested in working on this?

**Comment by richvdh** [comment]
Oh, it looks like it's awaiting review on https://github.com/matrix-org/dendrite/pull/2492.

**Comment by kegsay** [comment]
Blocked on review of the Dendrite PR.

**Comment by kegsay** [comment]
Closing as dendrite PR got closed.

**Pull request closed without merging**
