### PR TITLE
Document how to access the database for a homeserver after Complement runs

### PR DESCRIPTION
**Pull request by MadLittleMods**
Document how to access the database for a homeserver after Complement runs

Spawned from https://github.com/matrix-org/complement/pull/68

### CODE REVIEW

**Review by kegsay — COMMENTED** [review]
Unsure about this one. It's too specific to a specific HS impl and DB impl.

**Comment by MadLittleMods** [comment]
It's using the database that's defined in [`dockerfiles/synapse/homeserver.yaml`](https://github.com/matrix-org/complement/blob/3eaa98939578f56fa2cd1511556d110dfd8eaf1d/dockerfiles/synapse/homeserver.yaml#L31-L38).

I wanted to add one for Dendrite too but I haven't done it yet to be sure.


> **Synapse:**
> ...
>
> **Dendrite:**
> ...

**Comment by kegsay** [comment]
I don't feel this is the right place for this information. This is too Synapse specific, and then SQLite specific. It should live in the Synapse repo.

**Comment by MadLittleMods** [comment]
Moved this info to https://github.com/matrix-org/synapse/pull/10483 ⏩ 

Thanks for reviewing this @kegsay 🦢

**Pull request closed without merging**
