### PR TITLE
Remove dendrite skips in history visibility tests 

### PR DESCRIPTION
**Pull request by ShadowJonathan**
as https://github.com/matrix-org/dendrite/issues/617 has been resolved

### CODE REVIEW

**Review by DMRobertson — COMMENTED** [review]
CI says Dendrite is still failing. Is this to be expected?

**Comment by ShadowJonathan** [comment]
No, though this could either mean a problem with complement test, or a problem in dendrite's implementation of history visibility, I have it on a todo item to look at this later, but in the meantime i'll cc @neilalexander if he also wants to take a look at this.

**Comment by ShadowJonathan** [comment]
I've investigated the issue, looked at the tests again, and tested this PR against the dendrite main branch. The only conclusion I can pull is that https://github.com/matrix-org/dendrite/issues/617 is not resolved after all, as I can't see a commit or PR at the time that merges the functionality in dendrite.

**Review by S7evinK — APPROVED** [review]
Tests are now passing. :)

**Pull request merged**
