### PR TITLE
Fix the build for the master branch for synapse.

### LINKED ISSUE #184: Synapse tests run against `master` branch instead of `develop` by default
``` 
=== RUN   TestRestrictedRoomsRemoteJoinLocalUser
    msc3083_test.go:191: Deploy times: 6.570039ms blueprints, 3.985522787s containers
    client.go:370: POST hs2/_matrix/client/r0/createRoom => 200 OK (226.771354ms)
    client.go:370: POST hs2/_matrix/client/r0/createRoom => 400 Bad Request (5.686334ms)
    msc3083_test.go:204: CSAPI.MustDo POST http://172.17.0.1:49305/_matrix/client/r0/createRoom returned HTTP 400
```

https://github.com/matrix-org/complement/runs/3180791920#step:7:1029

### PR DESCRIPTION
**Pull request by clokep**
When the `master` branch of complement is built we want to run against the *default homeserver branch*, not the `master` branch (which will most likely always exist).

Fixes #184

### CODE REVIEW

**Comment by clokep** [comment]
I don't know for sure this will work until it's on `master` though. 😢

**Comment by kegsay** [comment]
Isn't the default branch `HEAD`? I use this in Dendrite upgrade tests.

**Comment by clokep** [comment]
From the GitHub docs:

> `GITHUB_HEAD_REF`: Only set for pull request events. The name of the head branch.

So yes, this doesn't seem correct. The other option is:

> `GITHUB_REF`: The branch or tag ref that triggered the workflow. For example, `refs/heads/feature-branch-1`. If neither a branch or tag is available for the event type, the variable will not exist.

I suspect I need to use that one.

I'm not sure what you mean by the default branch being `HEAD` though. `HEAD` is just a pointer to the commit you have checked out.

**Comment by clokep** [comment]
I think the updated version I have now will work correctly.

**Review by richvdh — APPROVED** [review]
seems plausible, if a bit fiddly.

**Pull request merged**
